import type { MockData } from '../types';

export const mockData: MockData = {
  vitals: {
    heartRate: '72 bpm',
    bloodPressure: '120/80 mmHg',
    bloodOxygen: '98%',
    pastReadings: [
      { date: '7AM', value: 72, yesterdayValue: 78, pastDaysValue: 65, type: 'Heart Rate' },
      { date: '8AM', value: 70, yesterdayValue: 75, pastDaysValue: 68, type: 'Heart Rate' },
      { date: '9AM', value: 75, yesterdayValue: 80, pastDaysValue: 70, type: 'Heart Rate' },
      { date: '10AM', value: 78, yesterdayValue: 82, pastDaysValue: 72, type: 'Heart Rate' },
      { date: '11AM', value: 73, yesterdayValue: 77, pastDaysValue: 75, type: 'Heart Rate' },
      { date: '12PM', value: 80, yesterdayValue: 85, pastDaysValue: 78, type: 'Heart Rate' },
      { date: '7AM', value: 120, yesterdayValue: 122, pastDaysValue: 118, type: 'Blood Pressure' },
      { date: '8AM', value: 118, yesterdayValue: 121, pastDaysValue: 119, type: 'Blood Pressure' },
      { date: '9AM', value: 122, yesterdayValue: 124, pastDaysValue: 120, type: 'Blood Pressure' },
      { date: '10AM', value: 125, yesterdayValue: 123, pastDaysValue: 121, type: 'Blood Pressure' },
      { date: '7AM', value: 98, yesterdayValue: 97, pastDaysValue: 99, type: 'Blood Oxygen' },
      { date: '8AM', value: 99, yesterdayValue: 98, pastDaysValue: 97, type: 'Blood Oxygen' },
      { date: '9AM', value: 97, yesterdayValue: 96, pastDaysValue: 98, type: 'Blood Oxygen' },
    ],
    recommendations: {
      'Heart Rate': 'Maintain a balanced diet rich in fruits, vegetables, and whole grains to support cardiovascular health.',
      'Blood Pressure': 'Reduce sodium intake by avoiding processed foods and incorporate potassium-rich foods like bananas, spinach, and sweet potatoes.',
      'Blood Oxygen': 'Ensure adequate ventilation in your living spaces and practice deep breathing exercises to improve lung capacity.',
    },
  },
  dailyActivity: {
    steps: '8,500 steps',
    sleepHours: '7.5 hrs',
    caloriesBurnt: '500 kcal',
    distanceWalked: '4.2 km',
    pastReadings: [
      { date: 'Mon', value: 8500, yesterdayValue: 9200, pastDaysValue: 6500, type: 'Steps' },
      { date: 'Tue', value: 9200, yesterdayValue: 6500, pastDaysValue: 10100, type: 'Steps' },
      { date: 'Wed', value: 6500, yesterdayValue: 10100, pastDaysValue: 7800, type: 'Steps' },
      { date: 'Thu', value: 10100, yesterdayValue: 7800, pastDaysValue: 8900, type: 'Steps' },
      { date: 'Mon', value: 7.5, yesterdayValue: 8.1, pastDaysValue: 6.9, type: 'Sleep Hours' },
      { date: 'Tue', value: 8.1, yesterdayValue: 6.9, pastDaysValue: 7.8, type: 'Sleep Hours' },
      { date: 'Wed', value: 6.9, yesterdayValue: 7.8, pastDaysValue: 6.5, type: 'Sleep Hours' },
      { date: 'Mon', value: 500, yesterdayValue: 550, pastDaysValue: 400, type: 'Calories Burnt' },
      { date: 'Tue', value: 550, yesterdayValue: 400, pastDaysValue: 600, type: 'Calories Burnt' },
      { date: 'Mon', value: 4.2, yesterdayValue: 4.8, pastDaysValue: 3.5, type: 'Distance Walked' },
      { date: 'Tue', value: 4.8, yesterdayValue: 3.5, pastDaysValue: 5.1, type: 'Distance Walked' },
    ],
    recommendations: {
      'Steps': 'Aim for at least 10,000 steps daily. Consider adding a short walk after dinner to aid digestion.',
      'Sleep Hours': 'Establish a consistent sleep schedule and create a relaxing bedtime routine for better sleep quality.',
      'Calories Burnt': 'Incorporate high-intensity interval training (HIIT) into your routine 2-3 times a week.',
      'Distance Walked': 'Try a new scenic walking route or include some inclines to stay motivated.',
    },
    sleepDetails: {
      performance: 80,
      hoursVsNeeded: { actual: 6, needed: 8 },
      consistency: 45,
      efficiency: 95,
      highStress: 2,
      weeklyPerformance: [
        { day: 'Monday', normalSleep: 98, averageSleep: 78, deepSleep: 58 },
        { day: 'Tuesday', normalSleep: 98, averageSleep: 58, deepSleep: 38 },
        { day: 'Wednesday', normalSleep: 98, averageSleep: 58, deepSleep: 78 },
        { day: 'Thursday', normalSleep: 98, averageSleep: 98, deepSleep: 68 },
        { day: 'Friday', normalSleep: 98, averageSleep: 38, deepSleep: 18 },
        { day: 'Saturday', normalSleep: 98, averageSleep: 78, deepSleep: 38 },
      ],
    },
  },
  location: {
    latitude: 34.052235,
    longitude: -118.243683,
    address: '123 Main Street, Los Angeles, CA',
  },
  healthHistory: [
    { date: '2023-10-25', summary: 'Check-up at County Hospital.' },
    { date: '2023-08-15', summary: 'Annual physical exam.' },
  ],
  emergencies: [
    { date: '2023-11-01', summary: 'Fall detected at 10:30 AM.', severity: 'critical' },
    { date: '2023-09-15', summary: 'Abnormal heart rate alert.', severity: 'major' },
    { date: '2023-07-20', summary: 'Dehydration warning.', severity: 'minor' },
  ],
  userDetails: {
    username: 'Jane Doe',
    age: 45,
    gender: 'Female',
    height: "5'6''",
    weight: '145 lbs',
    healthConditions: [
      { name: 'Hypertension', since: '2018', status: 'Managed with medication', medication: 'Lisinopril' },
      { name: 'Type 2 Diabetes', since: '2020', status: 'Controlled with diet and exercise', medication: 'Metformin' },
    ],
    medications: [
      { name: 'Lisinopril', dosage: '10mg', frequency: 'Daily', duration: 'Ongoing', condition: 'Hypertension' },
      { name: 'Metformin', dosage: '500mg', frequency: 'Twice daily', duration: 'Ongoing', condition: 'Type 2 Diabetes' },
    ],
    prescriptions: [
      {
        id: 1,
        name: 'Lisinopril 10mg',
        price: '$15.00',
        description: 'Blood pressure medication',
        frequentlyBought: true,
        date: '2023-10-25',
        doctor: 'Dr. Smith',
        doctorDetails: {
          name: 'Dr. Evelyn Smith',
          clinic: 'City Central Health Clinic',
          address: '456 Health Ave, Meditown',
          phone: '(555) 123-4567',
          license: 'MD-12345',
        },
        file: 'prescription_1.pdf',
      },
    ],
    allergies: [
      { name: 'Penicillin', reaction: 'Hives and swelling', precaution: 'Use alternative antibiotics' },
      { name: 'Peanuts', reaction: 'Anaphylaxis', precaution: 'Carry EpiPen at all times' },
    ],
    insurance: ['BlueCross BlueShield - Plan A', 'Medicare Part B'],
    recentHospitals: ['County Hospital', 'City Medical Center'],
    hospitalContacts: ['(555) 987-6543', '(555) 654-3210'],
    guardianContacts: ['John Doe - (555) 111-2222'],
  },
  emergencyContacts: [
    { name: 'John Doe', relationship: 'Spouse', phone: '(555) 111-2222', instructions: 'Primary contact', prioritized: true },
    { name: 'Mary Smith', relationship: 'Daughter', phone: '(555) 333-4444', instructions: 'Secondary contact', prioritized: false },
  ],
  allContacts: [
    { name: 'John Doe', relationship: 'Spouse', phone: '(555) 111-2222' },
    { name: 'Mary Smith', relationship: 'Daughter', phone: '(555) 333-4444' },
    { name: 'Dr. Smith', relationship: 'Primary Care', phone: '(555) 123-4567' },
  ],
  notifications: [
    { title: 'Medicine Reminder', description: 'Time to take Lisinopril', severity: 'important' },
    { title: 'Weekly Report', description: 'Your weekly health report is ready', severity: 'normal' },
    { title: 'Heart Rate Alert', description: 'Elevated heart rate detected', severity: 'critical' },
  ],
  quotes: [
    { text: 'Take care of your body. It\'s the only place you have to live.', author: 'Jim Rohn' },
    { text: 'Health is not valued till sickness comes.', author: 'Thomas Fuller' },
    { text: 'The greatest wealth is health.', author: 'Virgil' },
  ],
  ecommerce: {
    medicines: [
      { id: 1, name: 'Lisinopril 10mg', price: '$15.00', description: 'Blood pressure medication - 30 tablets', frequentlyBought: true },
      { id: 2, name: 'Metformin 500mg', price: '$12.00', description: 'Diabetes medication - 60 tablets', frequentlyBought: true },
      { id: 3, name: 'Vitamin D3', price: '$8.00', description: '1000 IU - 100 softgels', frequentlyBought: false },
      { id: 4, name: 'Omega-3 Fish Oil', price: '$18.00', description: '1000mg - 90 softgels', frequentlyBought: false },
      { id: 5, name: 'Aspirin 81mg', price: '$6.00', description: 'Low dose aspirin - 120 tablets', frequentlyBought: true },
    ],
  },
  appointments: [
    { id: 1, doctor: 'Dr. Smith', specialty: 'Primary Care', date: '2024-01-15', time: '10:00 AM', location: 'City Medical Center', status: 'upcoming' },
    { id: 2, doctor: 'Dr. Johnson', specialty: 'Cardiology', date: '2024-01-22', time: '2:30 PM', location: 'Heart Health Clinic', status: 'upcoming' },
    { id: 3, doctor: 'Dr. Williams', specialty: 'Endocrinology', date: '2023-12-01', time: '9:00 AM', location: 'Diabetes Care Center', status: 'completed' },
  ],
};
